name: APK Build with Warnings

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build with Kotlin Warnings
        run: ./gradlew assembleDebug --no-scan --no-daemon --warning-mode all

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: PrayerTimesWidget-APK
          path: app/build/outputs/apk/debug/app-debug.apk
